Greeting.create!(message: "Hello, nice to meet you?")
Greeting.create!(message: "Hello, good morning?")
Greeting.create!(message: "Hello, Goog evening?")
Greeting.create!(message: "Hi there.")
Greeting.create!(message: "it is a pleasure to meet you")